# Pre-commit hooks for cocode
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [--fix]
        
  # Black - Python formatter
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        
  # Mypy - Type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.0
    hooks:
      - id: mypy
        additional_dependencies: [types-all]
        args: [--config-file=pyproject.toml]
        exclude: ^(tests/|prototypes/)
        
  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
        
  # Check for secrets
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: ^(tests/|.*\.lock)$

# Local hooks
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
        
      - id: coverage-check
        name: Check test coverage
        entry: uv run pytest --cov=cocode --cov-fail-under=45
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]